---

- name: Install a managed PaperMC Velocity Proxy instance
  ansible.builtin.import_tasks: do_install.yaml
  when: mc_velocity_install

- name: Check for update on PaperMC Velocity Proxy instance
  ansible.builtin.import_tasks: check_update.yaml
  when: mc_velocity_check_update

- name: Update a PaperMC Velocity Proxy instance
  ansible.builtin.import_tasks: do_update.yaml
  when: mc_velocity_do_update

...
