---

- name: Prepare hosts for Minecraft Velocity proxy deployment
  ansible.builtin.import_tasks: installation/00_prepare_hosts.yaml

- name: Download Velocity onto host
  ansible.builtin.import_tasks: installation/01_velocity_download.yaml

- name: Initialize Minecraft Velocity Service on host
  ansible.builtin.import_tasks: installation/02_init_service.yaml

- name: First run
  ansible.builtin.import_tasks: installation/03_first_run.yaml

...
