---

- name: Stop Minecraft Server
  become: true
  ansible.builtin.service:
    name: "{{ mc__mc_service_file }}"
    enabled: true
    state: stopped
  timeout: "{{ (mc__service_timeout + 30) | int | abs }}"

- name: Run save script
  become: true
  ansible.builtin.command:
    cmd: sudo -u minecraft "{{ ('.', mc__save_script_name) | ansible.builtin.path_join }}"
    chdir: "{{ mc__mc_home_dir }}"

- name: Start Minecraft Server
  become: true
  ansible.builtin.service:
    name: "{{ mc__mc_service_file }}"
    enabled: true
    state: started
  timeout: "{{ (mc__service_timeout + 30) | int | abs }}"

...