---

# latest server.jar file from Mojang
- name: Minecraft Server Download URL
  ansible.builtin.script: mc_info.py url server "{{ mc__mc_target_version }}"
  args:
    executable: python3
  register: mc_server_data

# download latest server jar if all applications are met
- name: GET Minecraft Server
  become: true
  ansible.builtin.get_url:
    url: "{{ mc_server_data.stdout_lines[0] }}"
    dest: "{{ mc__mc_server_jar }}"
    owner: "{{ mc__mc_user }}"
    group: "{{ mc__mc_group }}"
    mode: "0755"
    force: true
  
- name: Create managed version file
  become: true
  ansible.builtin.template:
    src: .ansible_mc_version.j2
    dest: "{{ mc__mc_server_version_file }}"
    owner: root
    group: root
    mode: "0644"

...