---

- name: Prepare host for SMB
  ansible.builtin.import_tasks: prepare_hosts.yaml

- name: Install SMB mount as service
  ansible.builtin.import_tasks: mount_service.yaml
  when: not smb__mount_temp

- name: Install SMB mount as temporary mount
  ansible.builtin.import_tasks: mount_temp.yaml
  when: smb__mount_temp

...
