---

- name: Minecraft Velocity Proxy Download URL
  ansible.builtin.script: mc_velocity_info.py --version "{{ mc_velocity__target_version }}"
  args:
    executable: python3
  register: mc_velocity_data

- name: GET Minecraft Velocity Proxy
  become: true
  ansible.builtin.get_url:
    url: "{{ mc_velocity_data.stdout_lines[0] }}"
    dest: "{{ (mc_velocity__server_dir, mc_velocity__velocity_jar) | ansible.builtin.path_join }}"
    owner: "{{ mc_velocity__user }}"
    group: "{{ mc_velocity__group }}"
    mode: "0755"
    force: true
  
- name: Create managed version file
  become: true
  ansible.builtin.template:
    src: .ansible_mc_version.j2
    dest: "{{ (mc_velocity__server_dir, '.ansible_mc_version') | ansible.builtin.path_join }}"
    owner: root
    group: root
    mode: "0644"

...
