---

- name: First initial startup after installation
  become: true
  timeout: 60
  ansible.builtin.command:
    cmd: sudo -u "{{ mc__mc_user }}" java -jar paper.jar --nogui --initSettings
    chdir: "{{ mc__mc_server_dir }}"
    creates: "{{ (mc__mc_server_dir, 'eula.txt') |  ansible.builtin.path_join }}"
  register: mc_install_return

- name: Process EULA
  become: true
  ansible.builtin.lineinfile:
    path: "{{ (mc__mc_server_dir, 'eula.txt') | ansible.builtin.path_join }}"
    owner: "{{ mc__mc_user }}"
    group: "{{ mc__mc_group }}"
    regexp: '^eula'
    line: eula=true
  when: mc__accept_eula | bool and mc_install_return.changed

- name: Setup server.properties
  become: true
  ansible.builtin.template:
    src: server.properties.j2
    dest: "{{ (mc__mc_server_dir, 'server.properties') | ansible.builtin.path_join }}"
    owner: "{{ mc__mc_user }}"
    group: "{{ mc__mc_group }}"
    mode: "0644"
  when: mc_install_return and mc_install_return.changed

...
