---

- name: Setup Plex user group
  become: true
  ansible.builtin.group:
    name: "{{ plex__install_group }}"
    state: present

- name: Setup Plex user
  become: true
  ansible.builtin.user:
    name: "{{ plex__install_user }}"
    group: "{{ plex__install_group }}"
    password: "{{ plex__install_user_password_hashed }}"
    state: present
    shell: /bin/bash

...
