---

- name: Setup Host with Emby server
  hosts: testingvms
  tasks:
    - name: Request Emby-Server-Version Script
      ansible.builtin.get_url:
        url: >
          https://gist.githubusercontent.com/AkaBlur/
          c24b1f4fd6e0aa8ed7d18815eedc15cd/raw/
          844e48ab8edbe5b0505f07fb5760f44abb19dcf3/
          emby_get_latest_server.py
        dest: "/tmp/emby_get_latest_server.py"
        owner: "{{ ansible_user }}"
        mode: "0755"
      tags: download, local

    - name: Get latest Emby server version
      ansible.builtin.command:
        cmd: ./emby_get_latest_server.py
        chdir: "/tmp"
      register: emby_server_version_output
      changed_when: emby_server_version_output.rc == 0

    - name: Check xz-utils
      become: true
      ansible.builtin.package:
        name: xz-utils
        state: present

    - name: Install latest Emby version
      become: true
      ansible.builtin.apt:
        deb: "{{ emby_server_version_output.stdout_lines[0] }}"
        state: present

...
