---

- name: Setup Unbound as recursive DNS resolver for hosts
  become: true
  hosts: "{{ vm_hosts | default([]) }}"
  roles:
    - role: unbound
      vars:
        config_unbound: true
        unbound_access_control: "{{ unbound_access_allow }}"
        unbound_authoritative_zones: "{{ unbound_auth_zones }}"

...
