---

- name: Disable default stub listener from systemd-resolved
  become: true
  hosts: "{{ vm_hosts }}"
  tasks:
    - name: Service infos
      ansible.builtin.service_facts:

    - name: systemd-resolved present
      ansible.builtin.fail:
        msg: systemd-resolved.service not present!
      when: "'systemd-resolved.service' not in services"

    - name: systemd-resolved running
      ansible.builtin.fail:
        msg: systemd-resolved.service not running!
      when: "services['systemd-resolved.service'].state != 'running'"

    - name: Check resolved.conf.d directory
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create file 10-disable-stub-listener.conf
      ansible.builtin.copy:
        content: |
          [Resolve]
          DNSStubListener=no
        dest: /etc/systemd/resolved.conf.d/10-disable-stub-listener.conf
        owner: root
        group: root
        mode: "0644"

    - name: Restart systemd-resolved
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: restarted

...
