---

- name: Installs cronjobs from given local file
  become: true
  hosts: "{{ vm_hosts | default([]) }}"
  tasks:
    - name: Load supplied cronfile
      ansible.builtin.slurp:
        src: "{{ cronfile }}"
      register: cronfile_slurp

    - name: Check supplied cronfile
      ansible.builtin.set_fact:
        cron_data: "{{ cronfile_slurp['content'] | b64decode }}"

    - name: Get CRON minute
      ansible.builtin.set_fact:
        fact_cron_minute: "{{ cron_data.cron_minute }}"
      when: cron_data.cron_minute is defined

    - name: CRON default minute
      ansible.builtin.set_fact:
        fact_cron_minute: "*"
      when: cron_data.cron_minute is not defined

    - name: Get CRON hour
      ansible.builtin.set_fact:
        fact_cron_hour: "{{ cron_data.cron_hour }}"
      when: cron_data.cron_hour is defined

    - name: CRON default hour
      ansible.builtin.set_fact:
        fact_cron_hour: "*"
      when: cron_data.cron_hour is not defined

    - name: Get CRON day
      ansible.builtin.set_fact:
        fact_cron_day: "{{ cron_data.cron_day }}"
      when: cron_data.cron_day is defined

    - name: CRON default day
      ansible.builtin.set_fact:
        fact_cron_day: "*"
      when: cron_data.cron_day is not defined

    - name: Get CRON month
      ansible.builtin.set_fact:
        fact_cron_month: "{{ cron_data.cron_month }}"
      when: cron_data.cron_month is defined

    - name: CRON default month
      ansible.builtin.set_fact:
        fact_cron_month: "*"
      when: cron_data.cron_month is not defined

    - name: Get CRON weekday
      ansible.builtin.set_fact:
        fact_cron_weekday: "{{ cron_data.cron_weekday }}"
      when: cron_data.cron_weekday is defined

    - name: CRON default weekday
      ansible.builtin.set_fact:
        fact_cron_weekday: "*"
      when: cron_data.cron_weekday is not defined

    - name: Install new crontab
      ansible.builtin.cron:
        name: "{{ cron_description }}"
        minute: "{{ fact_cron_minute }}"
        hour: "{{ fact_cron_hour }}"
        day: "{{ fact_cron_day }}"
        month: "{{ fact_cron_month }}"
        weekday: "{{ fact_cron_weekday }}"
        job: "{{ cron_job }}"
        user: "{{ cron_user }}"

...
