---

- name: Setup Unbound as recursive DNS resolver for hosts
  become: true
  hosts: "{{ vm_hosts | default([]) }}"
  pre_tasks:
    - name: Install DNS root.key trust anchor package for system
      ansible.builtin.apt:
        name: dns-root-data
        state: present

    - name: Create unbound lib directory for root.key
      ansible.builtin.file:
        path: /var/lib/unbound
        state: directory
        owner: root
        group: root
        mode: "0777"

    - name: Copy trust anchor root.key for unbound
      ansible.builtin.copy:
        src: /usr/share/dns/root.key
        dest: /var/lib/unbound/root.key
        mode: "0777"
        remote_src: true

  roles:
    - role: l3d.unbound
      vars:
        unbound_listen_addresses: ["0.0.0.0"]
        unbound_access_control: "{{ unbound_access_allow }}"
        submodule_versioncheck: true

  post_tasks:
    - name: Chown for unbound trust anchor
      ansible.builtin.file:
        path: /var/lib/unbound/root.key
        owner: unbound
        group: unbound
        mode: "0644"

    - name: Chown for unbound lib directory
      ansible.builtin.file:
        path: /var/lib/unbound
        owner: unbound
        group: unbound
        mode: "0755"
