---

- name: Setup Host with Emby server
  hosts: testingvms
  pre_tasks:
    - name: Get latest Emby server version
      ansible.builtin.script: emby/emby_get_latest_server.py
      args:
        executable: python3
      register: emby_server_version_output
      changed_when: emby_server_version_output.rc == 0

    - name: Check xz-utils
      become: true
      ansible.builtin.package:
        name: xz-utils
        state: present

    - name: Install latest Emby version
      become: true
      ansible.builtin.apt:
        deb: "{{ emby_server_version_output.stdout_lines[0] }}"
        state: present

    - name: Generate RAMDISK script
      become: true
      ansible.builtin.template:
        src: emby/mount_transcode_ramdisk.sh.j2
        dest: /root/mount_transcode_ramdisk.sh
        owner: root
        group: root
        mode: "0700"

    - name: Add RAMDISK to cron at startup
      become: true
      ansible.builtin.cron:
        name: "Generate and mount RAMDISK"
        special_time: reboot
        job: "cd /root && /root/mount_transcode_ramdisk.sh > /var/log/mount_transcode_ramdisk.log 2>&1"

  roles:
    - role: nfs_setup

...
