---

- name: Sets the Timezone of Client
  become: true
  hosts: "{{ vm_hosts | default([]) }}"
  tasks:
    - name: Set the timezone
      community.general.timezone:
        name: "{{ timezone_string }}"

    - name: Restart cron
      ansible.builtin.service:
        name: cron
        state: restarted
