---

- name: Manage a Plex media server instance on hosts
  # NO become: true allowed to be added!
  # https://github.com/ansible/ansible/issues/83316
  # escalating ansible.builtin.script produces an empty entry from the PW
  # -> not allowed on this role!
  hosts: "{{ vm_hosts | default([]) }}"
  roles:
    - role: plex_setup

...
