---

- name: Update all apt packages
  hosts: all

  tasks:
    - name: Update apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: Check Reboot state
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Telegram Notification
      community.general.telegram:
        token: "{{ telegram_api_token }}"
        api_args:
          chat_id: "{{ telegram_chat_id }}"
          parse_mode: "MarkdownV2"
          text: "*Ansible*\nReboot required on:\n\t*{{ inventory_hostname }}*\n\t{{ ansible_default_ipv4.address | regex_escape() }}"
      when: reboot_required.stat.exists
