---

- name: Setup Unbound as recursive DNS resolver for hosts
  hosts: all
  tasks:
  roles:
    - role: l3d.unbound
      vars:
        unbound_listen_addresses: [ "0.0.0.0" ]
        unbound_access_control: "{{ unbound_access_allow }}"
        submodule_versioncheck: true