---

- name: Setup Unbound as recursive DNS resolver for hosts
  hosts: all
  pre_tasks:
    - name: Check services on host
      become: true
      ansible.builtin.service_facts:

    - name: Check if systemd-resolve is stopped (binds port 53)
      become: true
      ansible.builtin.systemd_service:
        name: systemd-resolved.service
        state: stopped
        enabled: false
      when: "'systemd-resolved.service' in services"

  roles:
    - role: l3d.unbound
      vars:
        unbound_listen_addresses: [ "0.0.0.0" ]
        unbound_access_control: "{{ unbound_access_allow }}"
        submodule_versioncheck: true

  post_tasks:
    - name: Run unbound-anchor to manually check for trust anchor
      become: true
      become_user: unbound
      ansible.builtin.command: unbound-anchor

    - name: Check if unbound is running
      become: true
      ansible.builtin.systemd_service:
        name: unbound.service
        state: started
        enabled: true
