---

- name: Setup Unbound as recursive DNS resolver for hosts
  hosts: all
  pre_tasks:
    - name: Check services on host
      become: true
      ansible.builtin.service_facts:

    - name: Check if systemd-resolve is stopped (binds port 53)
      become: true
      ansible.builtin.systemd_service:
        name: systemd-resolved.service
        state: stopped
        enabled: false
      when: "'systemd-resolved.service' in services"

    - name: Create unbound lib directory
      become: true
      ansible.builtin.file:
        path: /var/lib/unbound
        state: directory
        mode: "1777"
        owner: root
        group: root

    - name: Create trust anchor file
      become: true
      ansible.builtin.file:
        path: /var/lib/unbound/root.key
        state: touch
        mode: "0777"
        owner: root
        group: root

    - name: Register base root trust anchor ()
      ansible.builtin.copy:
        path: /var/lib/unbound/root.key
        content: ". IN DS 20326 8 2 E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D"

  roles:
    - role: l3d.unbound
      vars:
        unbound_listen_addresses: [ "0.0.0.0" ]
        unbound_access_control: "{{ unbound_access_allow }}"
        submodule_versioncheck: true

  post_tasks:
    - name: Update trust anchor for unbound user
      become: true
      ansible.builtin.file:
        path: /var/lib/unbound/root.key
        owner: unbound
        group: unbound
        mode: "0644"

    - name: Update unbound lib directory
      become: true
      ansible.builtin.file:
        path: /var/lib/unbound
        state: directory
        owner: unbound
        group: unbound
        mode: "0755"
